COMMAND_KEY = "COMMAND"
SUCCESFULLY_PROCESSED_COMMAND_KEY = "SUCCESSFULLY_PROCESSED_COMMAND"
ALERT_KEY = "ALERT"

# Command strings
CMD_STREAM_START = "STREAM_START"
CMD_STREAM_STOP = "STREAM_STOP"
MOTION_DETECTED = "MOTION_DETECTED"

